*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:04:13 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.0:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x101f760
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x101f760 pid: 30043 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30043)
spawned uWSGI worker 1 (pid: 30045, cores: 1)
spawned uWSGI worker 2 (pid: 30046, cores: 1)
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:04:51 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.0:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:08:46 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.0:8000).
bind(): Address already in use [core/socket.c line 769]
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.0:8000)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 06:11:05 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.0:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1e6ead0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1e6ead0 pid: 30043 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30043)
spawned uWSGI worker 1 (pid: 30064, cores: 1)
spawned uWSGI worker 2 (pid: 30065, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.0:8000)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 06:11:16 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.0:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x296cad0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x296cad0 pid: 30043 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30043)
spawned uWSGI worker 1 (pid: 30070, cores: 1)
spawned uWSGI worker 2 (pid: 30071, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.0:8000)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 06:12:11 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.0:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1867ad0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1867ad0 pid: 30043 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30043)
spawned uWSGI worker 1 (pid: 30075, cores: 1)
spawned uWSGI worker 2 (pid: 30076, cores: 1)
Thu Nov  9 06:12:31 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 06:12:31 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:12:52 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.0:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe04080
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xe04080 pid: 30083 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30083)
spawned uWSGI worker 1 (pid: 30085, cores: 1)
spawned uWSGI worker 2 (pid: 30086, cores: 1)
Thu Nov  9 06:15:38 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 06:15:38 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:15:45 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2764080
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2764080 pid: 30102 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30102)
spawned uWSGI worker 1 (pid: 30104, cores: 1)
spawned uWSGI worker 2 (pid: 30105, cores: 1)
invalid request block size: 21573 (max 4096)...skip
Thu Nov  9 06:17:25 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 06:17:25 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:19:48 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0xaa9140
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xaa9140 pid: 30117 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30117)
spawned uWSGI worker 1 (pid: 30119, cores: 1)
spawned uWSGI worker 2 (pid: 30120, cores: 1)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
Thu Nov  9 06:23:09 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 06:23:09 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:23:51 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 192.168.199.237:8000 fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x1bc9140
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1bc9140 pid: 30145 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30145)
spawned uWSGI worker 1 (pid: 30147, cores: 1)
spawned uWSGI worker 2 (pid: 30148, cores: 1)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
Thu Nov  9 06:32:32 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 06:32:32 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:32:39 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:44304 (port auto-assigned) fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0xd7c240
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xd7c240 pid: 30158 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30158)
spawned uWSGI worker 1 (pid: 30160, cores: 1)
spawned uWSGI worker 2 (pid: 30161, cores: 1)
spawned uWSGI http 1 (pid: 30162)
[pid: 30160|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 303 bytes} [Thu Nov  9 06:32:46 2017] GET / => generated 1716 bytes in 22 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
gateway "uWSGI http 1" has been buried (pid: 30162)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:44304)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 06:40:54 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to UNIX address /home/www/django_test2/uwsgi.sock fd 3
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x27c20b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x27c20b0 pid: 30158 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30158)
spawned uWSGI worker 1 (pid: 30173, cores: 1)
spawned uWSGI worker 2 (pid: 30174, cores: 1)
spawned uWSGI http 1 (pid: 30175)
Thu Nov  9 06:41:03 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 06:41:03 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 14:41:12 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 3
uwsgi socket 0 bound to UNIX address /home/www/django_test2/uwsgi.sock fd 6
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0xe27230
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xe27230 pid: 30182 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30182)
spawned uWSGI worker 1 (pid: 30184, cores: 1)
spawned uWSGI worker 2 (pid: 30185, cores: 1)
spawned uWSGI http 1 (pid: 30186)
[pid: 30184|app: 0|req: 1/1] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 06:56:48 2017] GET / => generated 1716 bytes in 30 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
Thu Nov  9 07:29:50 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Nov  9 07:29:50 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 15:30:20 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
writing pidfile to /tmp/django_test2.pid
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 3
uwsgi socket 0 bound to UNIX address /home/www/django_test2/uwsgi.sock fd 6
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x18fc2b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x18fc2b0 pid: 30276 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30276)
spawned uWSGI worker 1 (pid: 30278, cores: 1)
spawned uWSGI worker 2 (pid: 30279, cores: 1)
spawned uWSGI http 1 (pid: 30281)
Python auto-reloader enabled
[pid: 30278|app: 0|req: 1/1] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 07:32:10 2017] GET / => generated 1716 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
[pid: 30279|app: 0|req: 1/2] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 07:32:11 2017] GET / => generated 1716 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
[pid: 30278|app: 0|req: 2/3] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 07:32:11 2017] GET / => generated 1716 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
[pid: 30279|app: 0|req: 2/4] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 07:32:12 2017] GET / => generated 1716 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
[pid: 30278|app: 0|req: 3/5] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 07:32:12 2017] GET / => generated 1716 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
[pid: 30279|app: 0|req: 3/6] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 07:32:12 2017] GET / => generated 1716 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file ./django_test2/settings.py has been modified
[uwsgi-python-reloader] module/file ./django_test2/settings.py has been modified
gateway "uWSGI http 1" has been buried (pid: 30281)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30278)...
Gracefully killing worker 2 (pid: 30279)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 6 mapped to socket 0 (/home/www/django_test2/uwsgi.sock)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 08:34:25 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 3
uwsgi socket 0 inherited UNIX address /home/www/django_test2/uwsgi.sock fd 6
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x20a4130
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 26, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./django_test2/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/python3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python3/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/python3/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 30, in <module>
    'Did you install mysqlclient or MySQL-python?' % e
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'.
Did you install mysqlclient or MySQL-python?
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30276)
spawned uWSGI worker 1 (pid: 30353, cores: 1)
spawned uWSGI worker 2 (pid: 30354, cores: 1)
spawned uWSGI http 1 (pid: 30356)
Python auto-reloader enabled
[uwsgi-python-reloader] module/file ./django_test2/settings.py has been modified
[uwsgi-python-reloader] module/file ./django_test2/settings.py has been modified
gateway "uWSGI http 1" has been buried (pid: 30356)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30353)...
Gracefully killing worker 2 (pid: 30354)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 6 mapped to socket 0 (/home/www/django_test2/uwsgi.sock)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 08:38:51 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 3
uwsgi socket 0 inherited UNIX address /home/www/django_test2/uwsgi.sock fd 6
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x1385130
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 26, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./django_test2/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/python3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python3/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/python3/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 30, in <module>
    'Did you install mysqlclient or MySQL-python?' % e
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'.
Did you install mysqlclient or MySQL-python?
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30276)
spawned uWSGI worker 1 (pid: 30397, cores: 1)
spawned uWSGI worker 2 (pid: 30398, cores: 1)
spawned uWSGI http 1 (pid: 30400)
Python auto-reloader enabled
--- no python application found, check your startup logs for errors ---
[pid: 30398|app: -1|req: -1/1] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:17:53 2017] GET / => generated 21 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 30397|app: -1|req: -1/2] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:18:00 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 30398|app: -1|req: -1/3] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:18:00 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 30397|app: -1|req: -1/4] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:18:00 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 30398|app: -1|req: -1/5] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:18:00 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 30397|app: -1|req: -1/6] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:18:01 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
gateway "uWSGI http 1" has been buried (pid: 30400)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30397)...
Gracefully killing worker 2 (pid: 30398)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/www/django_test2
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 6 mapped to socket 0 (/home/www/django_test2/uwsgi.sock)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from django_test2_uwsgi.ini
[uwsgi-static] added mapping for /static => /home/www/django_test2/static
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 09:18:21 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 09 November 2017 11:30:06
os: Linux-3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/www/django_test2
detected binary path: /usr/local/python3/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django_test2/
your processes number limit is 11166
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8000 fd 3
uwsgi socket 0 inherited UNIX address /home/www/django_test2/uwsgi.sock fd 6
Python version: 3.6.3 (default, Nov  8 2017, 20:18:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x285e130
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 242880 bytes (237 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x285e130 pid: 30276 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30276)
spawned uWSGI worker 1 (pid: 30557, cores: 1)
spawned uWSGI worker 2 (pid: 30558, cores: 1)
spawned uWSGI http 1 (pid: 30560)
Python auto-reloader enabled
[pid: 30557|app: 0|req: 1/1] 192.168.199.253 () {42 vars in 704 bytes} [Thu Nov  9 09:18:22 2017] GET / => generated 1716 bytes in 23 msecs (HTTP/1.1 200) 3 headers in 95 bytes (1 switches on core 0)
